
# https://github.com/marketplace/actions/build-and-push-docker-images
name: docker build checker

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out Repo 
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: false
          tags: azukibar/discord-vc-notify:${{GITHUB_HEAD_REF}}-${{GITHUB_JOB}}
