# https://github.com/marketplace/actions/build-and-push-docker-images
name: docker build checker

on:
  push:
    paths:
      - 'Dockerfiles/**'
      - '.github/workflows/**'

jobs:
  docker-init:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  test-container:
    runs-on: ubuntu-latest
    needs: docker-init
    steps:
      - name: Build Test container image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfiles/test_Dockerfile
          push: false
          tags: azukibar/discord-vc-notify:test-GITHUB_REF-GITHUB_JOB

  amd64-production-container:
    runs-on: ubuntu-latest
    needs: docker-init
    steps:
      - name: Build Production container image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfiles/product_Dockerfile
          platforms: linux/amd64
          push: false
          tags: azukibar/discord-vc-notify:GITHUB_REF-GITHUB_JOB

  arm64-production-container:
    runs-on: ubuntu-latest
    needs: docker-init
    steps:
      - name: Build Production container image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfiles/product_Dockerfile
          platforms: linux/arm64
          push: false
          tags: azukibar/discord-vc-notify:GITHUB_REF-GITHUB_JOB

  amdv7-production-container:
    runs-on: ubuntu-latest
    needs: docker-init
    steps:
      - name: Build Production container image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfiles/product_Dockerfile
          platforms: linux/arm/v7
          push: false
          tags: azukibar/discord-vc-notify:GITHUB_REF-GITHUB_JOB

