# https://github.com/marketplace/actions/build-and-push-docker-images
name: publish_docker_image_latest

on:
  push:
    branches:
      - 'master'

jobs:
  docker-init:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

  login-hub:
    runs-on: ubuntu-latest
    needs: docker-init
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  login-ghcr:
    runs-on: ubuntu-latest
    needs: login-hub
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

  docker-hub-amd64:
    needs: login-hub
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Build amd64 and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfiles/product_Dockerfile
          platforms: linux/amd64
          push: true
          tags: azukibar/discord-vc-notify:latest

  docker-hub-arm64:
    needs: login-hub
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build arm64 and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfiles/product_Dockerfile
          platforms: linux/arm64, linux/arm/v7
          push: true
          tags: azukibar/discord-vc-notify:latest

  docker-hub-armv7:
    needs: login-hub
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build armv7 and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfiles/product_Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: azukibar/discord-vc-notify:latest


  ghcr-amd64:
    needs: login-ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Build amd64 and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfiles/product_Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/azuki-bar/discord-vc-notify:latest

  ghcr-arm64:
    needs: login-ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build arm64 and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfiles/product_Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/azuki-bar/discord-vc-notify:latest

  ghcr-armv7:
    needs: login-ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build armv7 and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfiles/product_Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: ghcr.io/azuki-bar/discord-vc-notify:latest
