# https://github.com/marketplace/actions/build-and-push-docker-images
name: publish_docker_image_with_tags

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    env: 
      VERSION: 0
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out Repo 
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Detect Tags
        run: echo ${{ github.ref }} | sed -e "s#refs/tags/v\(.*\)#VERSION=\1#g" >> $GITHUB_ENV
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfiles/product_Dockerfile
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: true
          tags: azukibar/discord-vc-notify:${{env.VERSION}}
      -
        name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./product_Dockerfile
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: true
          tags: ghcr.io/azuki-bar/discord-vc-notify:${{env.VERSION}}

