name: unit_test

on:
  push

jobs:
  unittest:
    runs-on: ubuntu-latest
    name: 'Unit Test'
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: run unit test container
        uses: ./.github/actions/unittest.yml
