name: unit test

on:
  push

jobs:
  unittest:
    runs-on: ubuntu-latest
    name: 'Unit Test'
    steps:
      - name: Python Unit Test
        runs:
          using: docker
          image: './Dockerfiles/test_Dockerfile'
