# https://github.com/marketplace/actions/build-and-push-docker-images
name: upload_dockerhub

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          push: true
          tags: azukibar/discord-vc-notify:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
